# Generated by Django 4.0 on 2021-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
                ('resume', models.TextField()),
                ('cost', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pizza-img')),
                ('title', models.CharField(max_length=190)),
                ('resume', models.TextField()),
                ('cost', models.CharField(max_length=90)),
            ],
        ),
    ]
