# Generated by Django 4.0 on 2021-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizaa_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main-pt')),
                ('title', models.CharField(max_length=150)),
                ('resume', models.TextField()),
            ],
        ),
    ]
