# Generated by Django 4.0 on 2021-12-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pizaa_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizaa_about',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
