# Generated by Django 4.0.1 on 2022-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='films.Actor'),
        ),
    ]
