# Generated by Django 4.0.2 on 2022-02-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_comment_created_date_alter_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
