# Generated by Django 4.0.2 on 2022-02-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
