# Generated by Django 4.0.3 on 2022-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message_id', models.CharField(max_length=200, verbose_name='СМС ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(max_length=10, verbose_name='Статус отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
