# Generated by Django 4.0.3 on 2022-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message_id', models.CharField(max_length=200, verbose_name='СМС ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
