# Generated by Django 3.2.11 on 2022-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Came',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('arrival_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
