# Generated by Django 3.2.11 on 2022-01-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAW', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='came',
            table='Came',
        ),
    ]
