# Generated by Django 3.2.11 on 2022-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAW', '0002_alter_came_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Went',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('Ishlab chiqarish', 'Ishlab chiqarish'), ("Qurilish bo'limi", "Qurilish bo'limi"), ("Energetika bo'limi", "Energetika bo'limi"), ("Mexanika bo'limi", "Mexanika bo'limi"), ("Iqdisod bo'limi", "Iqdisod bo'limi"), ('Ijro intizom', 'Ijro intizom')], max_length=20)),
                ('time_to_leave', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Went',
            },
        ),
        migrations.AlterField(
            model_name='came',
            name='section',
            field=models.CharField(choices=[('Ishlab chiqarish', 'Ishlab chiqarish'), ("Qurilish bo'limi", "Qurilish bo'limi"), ("Energetika bo'limi", "Energetika bo'limi"), ("Mexanika bo'limi", "Mexanika bo'limi"), ("Iqdisod bo'limi", "Iqdisod bo'limi"), ('Ijro intizom', 'Ijro intizom')], max_length=200),
        ),
    ]
