# Generated by Django 3.2.11 on 2022-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAW', '0003_auto_20220121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='came',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='went',
            name='time_to_leave',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
