# Generated by Django 3.2.11 on 2022-01-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAW', '0004_auto_20220121_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='came',
            name='arrival_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='went',
            name='time_to_leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CameAndWent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAW.came')),
                ('went', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAW.went')),
            ],
        ),
    ]
