# Generated by Django 3.2.9 on 2021-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialities', models.ManyToManyField(to='courses.Speciality')),
                ('teachers', models.ManyToManyField(to='courses.Teacher')),
            ],
        ),
    ]
